# Netlify Configuration for EzJob
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Directory to publish (Vite builds to 'dist')
  publish = "dist"
  
  # Build command
  command = "npm run build"

[build.environment]
  # Node version for builds
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Special handling for OG image to help with WhatsApp
[[headers]]
  for = "/og.png"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    Content-Type = "image/png"
    X-Content-Type-Options = "nosniff"

# Cache fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers for main pages
[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self' https:; frame-src 'none';"
